# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM node:22-alpine

# Enable corepack
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable

# Setup PNPM
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"
RUN mkdir -p /home/codespace/.pnpm-store /pnpm/bin \
  && chown -R 1000:1000 /home/codespace/.pnpm-store /pnpm

#Install Bun
COPY --from=oven/bun:1.3.11-alpine /usr/local/bin/bun /usr/local/bin/bun

COPY . /app
WORKDIR ${FOLDER}

ENV NODE_ENV=development

USER 1000:1000

# Apply PNPM settings to be consistent with devcontainer
RUN pnpm config set node-linker hoisted --global \
  && pnpm config set store-dir /home/codespace/.pnpm-store --global

EXPOSE 3000
ENV PORT=3000
ENV HOST="0.0.0.0"

CMD ["npm", "run", "dev", "--", "--host"]
